name: Test GulpIO2
on: push

jobs:
  test:
    name: Test GulpIO2
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # so conda is set up properly
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: conda info
      - name: Install dependencies
        run: |
          conda install -c conda-forge ffmpeg
          pip install -U pip setuptools pytest
          pip install -r requirements.txt
      - name: Install gulpio2
        run: python setup.py install
      - name: Run unit tests
        run: python -m pytest test/unit
      - name: Run integration tests
        run: python test/integration/system_tests.py
